---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:latest
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/vagrant/docker:/vagrant/docker"
    capabilities:
      - SYS_ADMIN
    network_mode: host
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: yamllint
