---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  vars:
    yum_packages:
      - python-pip
      - jq
      - git
      - gcc
      - python-devel
      - openssl-devel
      - libselinux-python
    docker_packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  tasks:
    - name: install EPEL
      yum:
        name: epel-release
        state: latest
    - name: install required yum packages
      yum:
        name: "{{ yum_packages }}"
        state: latest
    - name: Install docker python module via pip
      pip:
        name: docker
    - name: Install required packages for docker-ce
      yum:
        name: "{{ docker_packages }}"
        state: latest
    - name: Import Docker CE repository gpg key
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present
    - name: Add Docker CE repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        force: yes
        owner: root
        group: root
        mode: 0644
    - name: Install Docker CE
      yum:
        name: docker-ce
        state: latest
        update_cache: yes
    - name: Add the user 'vagrant' to docker group
      user:
        name: vagrant
        comment: Add the user 'vagrant' to docker group
        group: docker
        state: present
