---
# Manual steps required to install docker on CentOS are documented at https://docs.docker.com/install/linux/docker-ce/centos/
- name: Install required packages for docker-ce
  yum:
    name: "{{ packages }}"
    state: present
  tags:
    - packages

- name: Import Docker CE repository gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Install Docker CE
  yum:
    name: docker-ce
    state: latest
    update_cache: yes
  tags:
    - install_docker

- name: Add the user 'vagrant' to docker group
  user:
    name: vagrant
    comment: Add the user 'vagrant' to docker group
    group: docker
    state: present
  # FEATURE REQUEST: https://github.com/ansible/ansible/issues/15476. This issue has been open since 19 Apr 2016
  # handlers are not fired inbetween multiple roles as they are play scoped
  # In order to get round the issue described above, I have created multiple plays in the main playbook
  notify:
    - Enable Docker
